server:
  port: 8080

spring:
  # 是否开启启动横幅
  main:
    banner-mode: off

  datasource:
    druid:
      # 数据库地址
      url: jdbc:mysql://121.4.20.29:3306/mysql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      # 数据库用户名
      username: root
      # 数据库密码
      password: 123456
      # 数据库驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库连接池最大值
      max-active: 20
      # 数据库连接池初始值
      initial-size: 5
      # 数据库连接池最小空闲值
      min-idle: 5
      # 池中空闲连接大于minIdle且连接空闲时间大于该值，则关闭该连接，单位毫秒(5分钟，默认30分钟)
      min-evictable-idle-time-millis: 300000
      # 获取连接时最大等待时间，单位毫秒(1分钟)
      max-wait: 60000
      # 检测连接是否有效时执行的sql命令
      validation-query: select 1
      # 借用连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 连接空闲时检测，如果连接空闲时间大于timeBetweenEvictionRunsMillis指定的毫秒，执行validationQuery指定的SQL来检测连接是否有效
      test-while-idle: true
      # 空闲连接检查、废弃连接清理、空闲连接池大小调整的操作时间间隔，单位是毫秒(1分钟)
      time-between-eviction-runs-millis: 60000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #是否启用StatFilter默认值false，用于采集 web-jdbc 关联监控的数据。
      web-stat-filter:
        enabled: true
        #需要监控的 url
        url-pattern: /*
        #排除一些静态资源，以提高效率
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
      stat-view-servlet:
        enabled: true
        #内置的监控页面地址，例如 /druid/*，则内置监控页面的首页是 /druid/index.html
        url-pattern: /druid/*
        #是否允许清空统计数据
        reset-enable: false
        login-username: root
        login-password: root

mybatis-plus:
  type-aliases-package: com.face.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: off
demo:
  password: "123456"